title: ThermalNetwork Documentation
author: The NREL Buildings GHX team

repository:
  url: https://github.com/nrel/thermalNetwork
  path_to_book: docs
  branch: main

html:
  # use_edit_page_button: true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true  # Whether to add a link to your repository button
  use_issues_button: true
