name: Python Testing

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .[dev]
      - name: Unit tests
        run: |
          python -m pytest -v
